# Generated by Django 3.1 on 2020-10-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=5, verbose_name='NAME')),
                ('todo', models.CharField(max_length=50, verbose_name='TODO')),
                ('test', models.CharField(max_length=50, verbose_name='test')),
            ],
        ),
    ]
