# Generated by Django 3.1 on 2020-10-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lg', '0002_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='test',
        ),
    ]
