# Generated by Django 3.1 on 2020-10-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lg', '0003_remove_todo_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='new_test',
            field=models.CharField(default='NEW_TEST', max_length=50),
        ),
    ]
