# Generated by Django 3.1 on 2020-10-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lg', '0005_auto_20201003_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='apply',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
