# Generated by Django 3.1 on 2020-10-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lg', '0006_campaign_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='img_array',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='img_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
