# Generated by Django 3.1 on 2020-10-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lg', '0010_auto_20201005_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(max_length=100)),
                ('kor_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(max_length=100)),
                ('kor_name', models.CharField(max_length=100)),
            ],
        ),
    ]
