# Generated by Django 3.1 on 2020-10-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lg', '0012_auto_20201015_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='category',
            new_name='category_title',
        ),
    ]
