# Generated by Django 3.1 on 2020-10-15 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lg', '0013_auto_20201015_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='camp_category', to='lg.category'),
        ),
    ]
