# Generated by Django 3.1 on 2020-10-15 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lg', '0015_auto_20201015_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='camp_channel', to='lg.channel'),
        ),
    ]
